name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Vulkan
      run: sudo apt update && sudo apt search vulkan-sdk && sudo apt install vulkan-sdk -y
    - name: Build
      run: mkdir build && cd build && cmake .. && make
