name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: sudo apt update && sudo apt install xorg-dev libglu1-mesa-dev -y
    - name: Get Vulkan
      run: wget https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.tar.gz && mkdir vulkan-sdk && tar xf vulkan-sdk.tar.gz -C vulkan-sdk
    - name: Build
      run: git submodule update --init --recursive && source vulkan-sdk/1.1.126.0/setup-env.sh && mkdir build && cd build && cmake .. && make

  macos-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Vulkan
      run: wget https://sdk.lunarg.com/sdk/download/latest/mac/vulkan-sdk.tar.gz && mkdir vulkan-sdk && tar xf vulkan-sdk.tar.gz -C vulkan-sdk
    - name: Build
      run: git submodule update --init --recursive && source vulkan-sdk/1.1.126.0/setup-env.sh && mkdir build && cd build && cmake .. && make
